language: java
jdk:
- openjdk11
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check publish bintrayUpload -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew jar -x test -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_8a0a448a983c_key -iv $encrypted_8a0a448a983c_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: UHI9/fd5QFh/SdCtqlFLe0uuZ722VzgfOhnEUOgya7NEVZwieWBes6YpUdbBJgY6gF0s5AoqePMCjK3XbwaFTDNZW5YWKjGsSh/78KchHkGNxNhb1qgEQDWc1s0sR14klMN+HQ3yyGHd+UrPb+XL+Coso30+ApHeLG5WaNmGAQzLErV369XT3Lmay+hvbJCJYcY6/iy+W4JvW/ey2yShev3UJE4WIlD8PBwoVV08WceJMz4RHSJSYrySap+7GxE01jzXG/E63r4myq00mTyFPH/Fh9797yPImAo/uAyXhsnEj8VAAFQZaTXq9n0sESsCWEbjnFik0iznNC9xEjW/EC+EVzLZeIZ0BF1cgP6/zxtm3/8Bx3My1maW/GhvpInycgtwhlHwpdoqhK/NP0eJh7Joz+7YTgQMmXRCXHwWM4irsSimN1LSDF9IoEKyEb3NeG14x+qMkx7L60ecLLiMqhuXIyev6hWe75m5IMGCive6nbRSgrMa/ENJ3FsEppZ2af2jxrb/CB5VK7IYb2TZAYyTqLOpzeUq9IcHi7J+UxkqFiAMAcvN0veg+vQ8p0GyNm8bKyhi8LkPc2YagqKupOYGyxIa82+CuxvBGglBKS9dS77cDqzGrHriPSsrAmj3gGL3nSbBynBxWW5CD1DC+H670sD9t/uEfLrvtYbH7eU=
  - secure: QcttBJwa6EXCkSyXzuydCC6R5YTP4PWjg3fOqqSzjDI3MstRYzq4q3IoRGGFmZMhY/AjzWpVgPR1JapR2AmtGAVqIr67Bu5YRCe4wpY54C3eKTqOlFaNJOmHDLLrx4LB1W+rhReG13mEu79+ZAeC4EnBRHWY8vZ9Bfu4vIcmPfuNRlFqZGMmW4qQ0nlgsfR6J0idvoXNW3djqJtUTXkl/NTDs7MI9DTBOheEYhzsHFmsul4VpdRsgK5KKFT7/Osq+QeFQEF/jcWrndefqHjSRzci25JomiaY8KYEJRZARlN33VG8NMygy1Z0EPMd7/Y42Sk7InA4FeFcRJx7NW0SP2EZ1YWOw63nHk58uR/rW+m8Ob0DT5JzERLWmTRBcqOs0GsFebNiu0a3FP8SBqLrw4VBBl72XEUTrN1saAUVpt1ErKo5K99Yj0tZGcAIvSrf1rtfqeW+KeQ8Mhg62nZhs0QmO+39bUwujWps/Of/OHCX3zBWU0ixuUtoLgVUTiCRTiewo2B+rzfIAWcix6x1uMoDI+euZAuinTveORDf4NPyoOClOXEk+yye6J0S+qz0wFrktch6/WednsG3O9JRJWgFJmGU72Pm166WKMxwUKrrGklVmo9RAetkXxtvezWcbdd7zQGmCHupoeu8JnwBbM0dAcRsbjBTEwfIMXpTmgc=
  - secure: t3HY2oLixWJKYyuqoc61bjCBdtxW8/BqDoKq3Y1JAv+hL9JBwa0DxAlelzwgxbMuw1sFrvblqXNPeljnkS5+qn3d0MmfmjuOCqGKsNR3j/dOpGaJuFpGtR1zWFoN72dx/ZwC6URaedPpE1HCsl4Swq1fpok7aTxC5PGAJ578aV0diyQCAQq1xR9X21QM+I9I3judlupYf/6H1UULcw4Joi1eb2kswrupjBj/gtrrDC/zhJ1GPRu7t6jdfWoKiwFf6RSSNtZva4eS+kQ/6Eff7zuuU8ymgVRJD7t4xnoXlq1j1Vm9FtBrd+n4YRoaV5y5Rgq5gTjb4bkU71J6OJK7K63LB5Wu4O3NQUoLSn/Vzd4H5wjuL8NJZvTPCCj349IxqdqpP4uFMSBcjvJdUVe5/IpdMouQ0tsMMow5sUftrBuL7DZO9jhbZFMJSGs/lhMSfgip2YjsjH+29Zp8nymZFVLcb003rLpQHvQyXS7MTiq7zkZ7FCVIArg1mN5GMVW+XWa9bk/o9OAQeGuLAP9dbkjsqlxvQ12F6XTlPviGBO99IRcHqaIZ/ZplLCORtLVyODxyRBln0HPIEZJuGV+3IMJZC8nsC+Yu6PZ9+Llodisn+o79IHF7tvbSRyqvZbMbszAzOiC/nHSijayjkNndt/xIOPLZUufSW4fPmDu82Nc=
  - secure: IkrUENMxB9ondRZsAdWE/go2hU3WQ2l9XBhoWOPdx89+ewnKtQHG0eoK+nsbN9I7ke/11pI8fD0FYH2oIctr3XXVz4Go7GRtsolraol7JEmdFeODHunF8f1b7244NfJu6topq6oCU7ii9N3Eff0z4roTLrUjnfW8XnYga19GhtwiXwQ++6Ebk0RLN6oNdJg+EtbDSnPnXTDRJsICFPeo92s3geCr4Ecgs93B6Zfk1GYxwG72VsCOqVo9yrXu5xw136Gypeh7GGptU1RMptx1cmdH73E8UjCnmEsfszhq3YxDph+9MFoGW1xA8eHKuh2raEIUYaJnhCtzVYaetU5hSw8TudzDSc4q5rlruVRXChoO0xDczJocnPI6mTUS4gIZW1OvzaVIgQuPYRyNYmZxhnxKSGLkcWRzrJ/OKEcZv7qSW+NqznNIuDb4nUQ6EVE+mEEe9d3GH2hsgO5x7W92z87d4nLJMC42jZCGEVi4ZcBUqqR6GKn7frQ3wyZbrE6760OifdwQDUXB7pSmER3P9U3IAQwqkd+ljp6p5A4vpwOoa/0OqNBPTSBUgwFr1r2kNeq5f7FJQVIRgiqZKPiq/jQesXzRGaqx6eGK8beC5G1fS8meCjLrQFEWxfd5PhHoEBPdJEG0oVxeoXhn+IOitD9E0qEf+dnw05VGcvDuHo0=
  - secure: kbVmqRkOtqvS2sjmdH07Zpjj3Gi4qU8P3WLN6PS94+IRgNCfoit1rHUJ4HXBY1A3xUKZfvVg/vurFSdct3LIYv/5QjwMX8rLPQaVfNQJmFHxM0LdeOC8L+MwhSDztqzG6hw9P1cVTXlvV/CRP/laeUFZZ9DxHhASRCnvpyyOHFPVmayH0k5vs9hVz+oltbAd3zuOsTgwgQB8FylfmhXJ60C+1ntHgyVo6q3iAzkPKcsPAqdzS0wfAVtgqvN+COaKVeXAZ/F+Qhr2QSeCSyKc2jiwdFfB+bfkqkLa9QXUWJgI5Jh7eOd19IugQ2tWgK4LB3iJOZj2p/qBbjN99n288SxwielJPiu1Jz2KJATCChGpsnGAXJiWtBitx+nEcAeMD/XfwCi1qlAIAW2JTBWFMMB76FrCY+OrCJLP1R/vIxHSgZH22djTrIRkdiFR60DWPjNUYF/i5gy910d1h+HRgZG+ZmztrKihtH7k2gKdDE5xa4BmKP0l+uPOBL6dGEOnCAfxXcx9IFYlt55og3YWr0XTvQV2vX4hWHywF+hDmtXfySvm8OIbO3Q/JQ9rcKhumjZfONMVRmoHaQZC3Hx4DmtgjkwFow7bkh1NiPBJJHm1Lu29PKzsOJXqHo8i6hpLgPyX3m+V8/FZLW+Fycjsmm2jQH46VE84lNHOsE8DzqI=
  - secure: fedfv52UH2htdYOwLBETkviQhhKpxTcZuuQjok4olxR6mvNYxlFFUDsel2tHE2Thkr5d2y7uV/MeLagoT86nObHWJ1nlyAtSAT5cFrH+GR6EP6Ci1egl/bO0khbrrrmViVhXhTrFYafQatPs77EIYaWnGYsu5613iPBTy0cDxhBjJ2e8UHlgB7pEwBvjbR7NraIecWYB3k1F/xbhLeW0Ajqvox2rmjN4o1ou2KiVdvnGxjkDVL1vylBKBj7452GVn+9DV4j5y6vBd33OlCAswdjz91cosaE5KysPGgg9W4SatcKkSe87Ed000kcntwjy4ATpUNyqnPNgrcL/JAkANMi6kTuJ5LD9rssfXHVLvzT6C8xMfjq5PMkekd5/0N6f03Bw/GSoTUhEULcolZq/9ca2WJ2MKWL45iaxgsU3aJRZreJ3pVDNgxq7WlSppmXdUdSkrfjQcanBpEaroqg6URHj42xHQqNT/zLdq01JaMSrLaLuSUc8wj5kqqJui3grBtk/FJg53EniZqG9YJmMQNGwq8jikYFH0XiBrt+kDq/MWg2zOTJdyaFu68PqxiUQBKe2TtV/1bN/5w0MZ/QSHch99bSqK4t02CfMtZbcDNLvXmX3rlAd6dleSo0wFsW+IpNwc4gbI3KzWHNnHE9EX1nNZrVRxTcO2LgwllpKwO8=
