language: java
jdk:
- openjdk11
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: skip
test: skip
jobs:
  include:
  - stage: build pull request
    script: "./gradlew check jacocoTestReport"
    if: type = pull_request
  - stage: build master
    script: "./gradlew check jacocoTestReport publish"
    if: branch = master AND NOT type = pull_request
  - stage: build and stage release
    if: branch =~ /release/
    script: "./gradlew check publish -Pversion=${TRAVIS_BRANCH#'release/'}"
  - stage: release
    if: branch =~ /release/
    script: "./gradlew closeAndReleaseRepository"
  - stage: github release
    if: branch =~ /release/
    script: "./gradlew check -Pversion=${TRAVIS_BRANCH#'release/'} && ./scripts/github-release.sh"
after_success:
- bash <(curl -s https://codecov.io/bash)
before_install:
- |
  if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
    openssl aes-256-cbc -K $encrypted_8a0a448a983c_key -iv $encrypted_8a0a448a983c_iv -in web3j.asc.enc -out web3j.asc -d
  fi
env:
  global:
  - secure: BDoxX7JNNAk2SCd7MCNxas2Xsa3dh2P9GuX4n519XMxBKmZ2r6gjWGoTxwMwS0nLfO/qXU9Bg/xM3PUunF6n1wNSMi+XX4lm2x0jP02G+g4mKImqoZPnlNSIl7+ZiPsS9iPVgfa9qYxSNzuzrDMPS8qx5Q/39XualWyXiRwnR1s0N8uknhovHbSFLvFZERYDrtb7O997KqaUxmc71v9ulZJp0e5drJ5jmVFbbm6FnYAlXZVPAW6ilz2bzXtY8x8GY0M4olA2GI3rWD90eaAzjUax4NfUGQT7RKSLOl3omFflVsrT0xBKEtBE4arpuujcogQiggz/VqfKZGkkqJfO20+OPqmy7vsewQzV/kOcs7WUGlzWajNsDlVYhNEm6L8UWA5jpCsnpr7LVgLEfh5Su6WzU3i6J1MVHusJwkvqB1oWUY3l4CMdFLogk+lxLmqrgNZzmftuuQ5/HXU9eTlIt/FolJ8T9AK0hUExG24eHMSDwmtEsSfkulE4eW/IwM9ZG/UBNKEfREG4EBT4i07VtCly2mVRSM59ePO47+yBXeNcZqinMprA2xuekUGyp86ugon9ie6g5YngRKWCi8lqh8vwo3GIkxZsgChcQXrDFenbzQCm+TPUhy32hbxyn68Je4ubMfgKA62x1U3CTiIoL9p5MIpfGzpyK7nT7kuhWYk=
  - secure: nf30u6KUs9T2oBTb3RKuEYhWKigunwmS1+xBx/ufMW4NAxqZe3jTbCgFfTu7XQksGHL5wRzDGGKElXTWIhk2l5kZ/1Rfk8kJ+WTPFv49sdeimQ3Vs//OxEFRKpkx4ZUGPtV8eKPccfKpNqD9A0zVj2ebD/ZUUPysy6XcVh3kgQDtn6SBpSOnuXeoJFJ1jVq2AIkBgjGQk9dyCZiWb2nvCpyl/tK1Vip3Cc5Mtu7uATR8skO+FL9EKCwgA7GDvQxOTtenGUEgH5wCx9hBZ/0/6+TKN9lt118c83p4Sb0SkwV+lxHNooRFABO8W29C2nTu/IQ54DhxI4hGUoVWdVS+NnB1NpF0U32hyIIh+7haOKqdZcP0xwlSKix9HiIJeLXTAIUYTtWkh/Vh1Fi1zXpvIvGLQUeZEpIskxYHFQKL3OAN1Aqc/aZZi4nJESljdV5stpC2onBsXCsqbLfdHHdQ1p60wRcdhr0D/U5UISgaA/5aOF8kSzSYQOXQFCrid1g+yMQm/GhcjPf0xhFp/8XNXLrNGAg0kVFWiAjnWWGqIEUee273oo5U57Yry0v/n5kMukEl0vYIwv3PL+8478h8ztc1u5xlRNw9Vhf4aS35RqQWEhgCgtMD2blGEO3e7G/zFkbgfkK3EWkvCzMqJONCD2707cZcQRYoaTfuCUQBVno=
  - secure: Z3H1TjmSMd+pR0D286sL1yvyb8YdYHExDBUsrCcesBmFvaWbX1EFibrFxGrWWdp0Ecejmx71DV9n+nzgr6hkVSK63lv4c7k/clal97/WIcDi8CYhJQgRYvgZiDNFfxB5lumxYZsCSdZZe8ZA0KTJDypY6Vt6fR5POJhco4qGx92fLHlRmvmF+iaNGKy6nxTSRFEIcGoTpYtnBK8WgoDp6MA5d77NvSdW5sI7I7VeXdIoSJ12OyHvsd7hyygCel7UXGA02ZW65G8tyqyD+/yxJ59DXZ/T0/NENzJYpbqqqNnTXF7yuDdQraQjX2std0JZ/YcfYGSwBbBBjCtKooxYn2Bo2w3238r32acBiJ48efiPS8lOxNRrxcLuLgn2vkZsTHquLdt/HzApPkBA3kHGLk9uUpbRMde82srBMEg/vycUawUsfXlKpbqtxRMqwcJebqIyEqTDZoSDBS/QX1jyYn51My0syTxWshugT6Jh/zPV6iYxxWZPUBL8XB6xc7A4JivOR4cJUcQC979IsyVLC02TL6eHfPo1Uas70KaQfVu+szbVb8maar017LamzEQBo0GPtPR4i04Z/wAHDhb/yoZobKBTz1fnpSNfjHQd4VVwfgZZ5aIve0qjmqSzMNd9ks+xsIs+RQnZHrVcY+I0tueIBngYsdeIGLpdAEVdRPc=
  - secure: W/TjSUb8vkO0g9lAvlhtIqCfHh0SX/uAsaqN9NwkMs0cVzwckkfD4dPIEm566ZhK6Zf+iHgOMN9vVwebBAaZemR/BZIBbvBnkF9bToLcU+ywopMK+ogHQppb9wRYBYkYODwWFIYGsh2wTNr6qAuMQ4Wnx5G8MXP5oZG8/110bgkj5yLaT8zICEAXKzbRNlgzmDEjOJD//YKG1ScnnI8NPt71ZPPYJ85XiCpYfJ5ka0MvMsmSCT4t+OpVv+JR9ZbChlRTlKKXjG73X/A0syCMxycIEbFlVzygYaRAQmzCXSztX5oNcksX1Ka6CztPRC5XT2Jvjww64Nuo7uWegeNNKoBzMfQuy557/Q+y/LkuAsYE57Ua4LCyUybpqziV3T0pJRQS8ml5CqKdZwazUcT/4KlQKUUz6MIGyU3KTA9NI64n6NINXr5kEU/L+qDVocW5bS7qsqZdWAhtr6m+OCMp5xuKttus1CCCAK2YJTy5Xz1Z7UJ5g0hGjf0geQcpQwLufMpMcEpK1t9n/lcPuHmp+cYgn++HyvdrQ5G+pAQz/+1juGv3CJIOkRG75tBR8WRjefvYTUNfnYjYdR5dZUlzQK/PWJgMXfN/iu7eRaobBC8C8ntJYgBaoMq7F6/H13EVbV1O0xyKo3KLw5FySszJfQsZ/hzb8NjJ5szbqJNxsrk=
